# Generated by Django 4.2.26 on 2025-11-19 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=255)),
                ('mentor_name', models.CharField(blank=True, max_length=255)),
                ('date_joined_company', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('avatar', models.CharField(blank=True, choices=[('robot', 'Robot'), ('astronaut', 'Astronaut'), ('worker', 'Worker'), ('manager', 'Manager'), ('seller', 'Seller')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
